### ISSUE TITLE
WARC revision 1.1 (augmentation): propose a specific profile for the management of diffs in the revisit records

### ISSUE THREAD

**Issue by cleymour** [iipc/warc-specifications#11]
Definition: revisit records may be used to store the diffs of a deduplication process. A new profile should be proposed that takes this case into account.

Decision: a paragraph should be written that describes this new profile, as chapter 6.7.4. of the standard.

Besides, in the sentence (p. 4): “All ‘warcinfo’, ‘metadata’ and ‘revisit’ records shall not have a payload”, the revisit records should not be listed (NB from Clément: not sure about that: is the diff a “payload” or a “block” of the record? If the HTTP protocole response is included, the diff should be considered a payload).

Action: Andy Jackson from BL, Eld Zierau from KB and Kristinn Sigurðsson from NL of Iceland to propose a formulation.

**Comment by saraaubry** [comment]
Following discussions during the ISO working group meeting on November 16-17, 2015:
the topic is not mature enough to state impact on revisit records.
So the issue is out of the 1.1 revision.

**Comment by saraaubry** [comment]
Not included in WARC 1.1. Superceeded by #30
