### ISSUE TITLE
Add WARC implementation guidelines

### ISSUE THREAD

**Issue by kris-sigur** [iipc/warc-specifications#2]
See further here: http://netpreserve.org/resources/WARC_Guidelines_v1.pdf

Needs to be incorporated in this repo.

**Comment by ato** [comment]
Done! https://iipc.github.io/warc-specifications/guidelines/warc-implementation-guidelines/

I did a rough semi-manual markdown conversion from the PDF. There's probably a few formatting errors remaining. I also totally punted on the footnotes. But hey it's in the repo now!
