### ISSUE TITLE
WARC revision 1.1 (clarification): record the base encoding of digests

### ISSUE THREAD

**Issue by saraaubry** [iipc/warc-specifications#29]
Detailed description of use cases to come by Eld.

The following changes have been integrated in the revised ISO draft during the ISO working group meeting on November 16-17, 2015:
In the examples in sections 5.8 and 5.9, add
WARC-Block-Digest: sha1:AB2CD3EF4GH5IJ6KL7MN8OPQ
or 
WARC-Block-Digest: sha1_Base32:AB2CD3EF4GH5IJ6KL7MN8OPQ

**Comment by anjackson** [comment]
Personally I would recommend against the ```sha1_Base32``` form, and just use the ```sha1``` and allow the encoding to be implied. I realise it is frustrating that there is no standard scheme for explicitly stating the encoding, but arbitrarily adding one to *this* standard when it is supported by *no* tools (and is likely therefore to break interoperability) is not a good idea.

There are better places to try to resolve this refinement, e.g. <https://tools.ietf.org/html/draft-seantek-sha-uris-01>

**Comment by kris-sigur** [comment]
I agree with @anjackson 

This is just going to be a massive pain in the err.... *tools*. Most likely it will be ignored by the tools potentially causing confusion in the future.

**Comment by saraaubry** [comment]
@anjackson, @kris-sigur we rolled back on the changes. This information shall be specified into a metadata or warcinfo record if needed.

**Comment by elzikb** [comment]
The reason for this suggestion was that the current practice does not make a precise definition of the algorithm, however the standard does not exclude the possibility of being more precise, and specifying the informaiton in the warcinfo is also an aceeptable recommondation/example.

**Comment by elzikb** [comment]
I think it would be a good idea to give more guidance on this via the IIPC group, since there are no formal precose description of which digest algoritrhm are commonly used.

**Comment by saraaubry** [comment]
Not included in WARC 1.1. Dismissed.
