### ISSUE TITLE
Make master branch to be the default

### ISSUE THREAD

**Issue by ibnesayeed** [iipc/warc-specifications#58]
I suggest we synchronize the `master` branch with `gh-pages` branch, make `master` branch as the default, delete `gh-pages` branch, and set GitHub Pages to build from the `master` branch instead. Current setup is probably a result of the legacy behavior of GitHub pages where `gh-pages` branch was the only way to host static sites. The downside of current set up is that everyone who forks the repo automatically gets a replica of the site deployed under their namespace. By changing it to `master` this will not happen automatically for everyone, while they will have the choice to deploy one for testing if they want to.

**Comment by ato** [comment]
Good point. That's done.
