### ISSUE TITLE
Truncated responses are not anymore required to be marked with WARC-Truncated since 1.1

### ISSUE THREAD

**Issue by JustAnotherArchivist** [iipc/warc-specifications#62]
The WARC/1.0 specification contained the following sentence in the [response record definition](https://github.com/iipc/warc-specifications/blob/95cdcfbb5720d93ca65e3c577da47f6d1ffff653/specifications/warc-format/warc-1.0/index.md#response):

> When a 'response' is known to have been truncated, this shall be noted using the WARC-Truncated field.

As far as I can see, the 1.1 spec does not have an equivalent statement. The definition of `WARC-Truncated` only mentions that the field *may* be used to indicate truncated responses. [Revisit records with identical payloads](https://github.com/iipc/warc-specifications/blob/95cdcfbb5720d93ca65e3c577da47f6d1ffff653/specifications/warc-format/warc-1.1/index.md#profile-identical-payload-digest) are required to use the `WARC-Truncated` field, but this obviously doesn't apply to all other reasons for truncation, like timeouts or size limits.

**Comment by ato** [comment]
Since it's present in the [BNF final drafts](http://bibnum.bnf.fr/WARC/) and the missing chunk of text aligns exactly to a page boundary I'm assuming it was unintentionally missed during the creation of the markdown file. I've added it back.
