### ISSUE TITLE
Duplicate definition of the payload of request records and insufficient definition for truncated responses

### ISSUE THREAD

**Issue by JustAnotherArchivist** [iipc/warc-specifications#75]
The definition of the WARC-Payload-Digest header field also defines the payload for any `application/http` block ([section 5.9](http://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#warc-payload-digest)), requests and responses. The corresponding paragraph was removed from the response record description but remains in that of request records ([section 6.5.2](http://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1/#http-and-https-schemes-2)).

There is one notable difference though: section 6.5.2 makes a mention of truncated request blocks, but section 5.9 does not. This means that the payload of a truncated response record is not properly defined in WARC/1.1.

**Comment by ato** [comment]
This appears to have had the same cause as #62, several paragraphs were lost from section 6.3.2 during conversion to markdown. The missing text was restored by #81.
