### ISSUE TITLE
warcfile offset: compressed or uncompressed?

### ISSUE THREAD

**Issue by isoos** [iipc/warc-specifications#76]
The current state of the [specification](https://iipc.github.io/warc-specifications/specifications/cdx-format/openwayback-cdxj/#appendix-c--warcfile-uri-scheme) leaves the `#offset` bit in `warcfile:<warc-filename>#<offset>` ambiguous:

```
The <offset> is the number of bytes from the start of the WARC when the relevant record begins.
```

If we track both the compressed and the raw offsets, which should go here? How about both? Or a range maybe?

**Comment by ato** [comment]
In practice it has to be the raw offset in the underlying file as this is what is needed to seek to the start of the record to begin reading it. Note that I don't think the OpenWayback CDXJ proposal has had much adoption. I've mostly only heard people in the community talking about [Pywb-style CDXJ](https://pywb.readthedocs.io/en/latest/manual/indexing.html#cdxj-index) which uses different field names.

**Comment by ato** [comment]
The OpenWayback CDXJ proposal has been withdrawn. #77
