### ISSUE TITLE
WARC revision 1.1 (clarification): scope of the standard

### ISSUE THREAD

**Issue by cleymour** [iipc/warc-specifications#8]
Definition: the introduction and the scope of the standard mostly acknowledges use cases related to web archiving. However, some institutions are using WARC format to store other kinds of digital content.

Decision: the introduction and the scope should state more precisely that WARC originated from web archiving community but should also acknowledge its use in other communities.

Action: Clément Oury to propose a formulation.

**Comment by cleymour** [comment]
Proposal to rewrite the 5th paragraph of the introduction section: 
"The WARC format offers a standard way to structure, manage and store billions of resources collected from the web and elsewhere. It is used to build applications for harvesting, managing, accessing, mining and exchanging content. While it represents the unique standard format for web archives, it has been adopted beyond the web archiving community, notably to store born-digital or digitized books and serials. The way WARC files will be created and resources stored and rendered will depend on software and applications implementations".

**Comment by kris-sigur** [comment]
@cleymour Might I suggest not closing an issue until the necessary text changes have been made to the working 1.1 document. I've created a pull request (#26) for the changes you proposed.

**Comment by cleymour** [comment]
Thank you Kristin. I'm not used to GitHub... 
I have two remarks on my own proposal:
- I added the notion of "mining" web archives
- I removed the reference to Heritrix as it is generally better for an ISO standard not to quote any implementation (to stay as neutral as possible)

**Comment by saraaubry** [comment]
The following paragraph has been integrated in the revised ISO draft during the ISO working group meeting on November 16-17, 2015 : 
Proposal to rewrite the 5th paragraph of the introduction section:
"The WARC format offers a standard way to structure, manage and store billions of resources collected from the web and elsewhere. It is used to build applications for harvesting, managing, accessing, mining and exchanging content. While it represents the unique standard format for web archives, it has been adopted beyond the web archiving community to store born-digital or digitized materials. The way WARC files will be created and resources stored and rendered will depend on software and applications implementations".

**Comment by saraaubry** [comment]
Included in WARC 1.1
