### ISSUE TITLE
Gemini as a protocol for the WARC-Protocol field

### ISSUE THREAD

**Issue by acidus99** [iipc/warc-specifications#85]
### Protocol name

Gemini

### Protocol identifier

"gemini"

(By design, the Gemini spec has no version numbers)

### Specification URL (optional)

https://gemini.circumlunar.space/docs/specification.gmi
https://en.wikipedia.org/wiki/Gemini_(protocol)

There are some existent WARCs containing Gemini traffic on the Internet Archive as well:
https://archive.org/details/mozz-gemini-crawl-2020-1
https://archive.org/details/mozz-gemini-crawl-2020-2
https://archive.org/details/mozz-gemini-crawl-2020-3

### Other

Gemini is a simple application protocol similar to HTTP/0.9, that runs on top of TLS. There exists around 3000 servers, and ~1M URLs. [I run one of the search engine for it](https://github.com/acidus99/Kennedy), with a crawler that generates WARC files, which are then consumed by the search index as well as a Wayback Machine-style archive.

If I understand the WARC-Protocol proposal correctly, because Gemini runs on top of TLS, implementers would use 2 `WARC-Protocol` fields like this:

```
WARC-Protocol: tls/1.3
WARC-Protocol: gemini
```

**Comment by ato** [comment]
Thanks! I've added Gemini to the definitions in the WARC-Protocol proposal (#42).
