### ISSUE TITLE
WARC-Protocol addition proposal: Gopher

### ISSUE THREAD

**Issue by TheTechRobo** [iipc/warc-specifications#87]
Gopher is a rather old spec pretty similar to HTTP/0.9 and the like. https://en.wikipedia.org/wiki/Gopher_(protocol)

Despite being pretty abandoned, there are still servers on the Internet using it. It would be nice to have its support in the WARC format.

A memo (not standard) describing the format can be found here: https://datatracker.ietf.org/doc/html/rfc1436

**Comment by ato** [comment]
Thanks! I've added Gemini to the definitions in the WARC-Protocol proposal (https://github.com/iipc/warc-specifications/issues/42).
