### ISSUE TITLE
Clarification on License for “The WARC Format 1.1 + community annotations”

### ISSUE THREAD

**Issue by ryan-minato** [iipc/warc-specifications#99]
I am writing to seek clarification regarding the license of the textual content described in the WARC specification [The WARC Format 1.1 + community annotations](https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.1-annotated). 

I would like to know if I am permitted to use the original text in my own warc i/o library.

**Comment by ato** [comment]
My guess would be probably not. My understanding is that the WARC spec is not available under a fully open license and the text here is permitted for the purpose of standards development.

For what it's worth, I hereby grant permission to use, reproduce and make modified versions of the text of the annotations in that file that I personally am the original author of. This statement does not extend to the base text of the specification itself nor to any text originally authored by others.
